/*procedimientos del ALERTA, EXEC ALERTAPROC @ID = INT,@STOCK = INT,@USUARIO = INT,@MINIMO = INT,@TIPO = NVARCHAR(10);*/ 
CREATE PROCEDURE ALERTAPROC	(@ID INT,
							@STOCK INT,
							@USUARIO INT,
							@MINIMO INT,
							@TIPO NVARCHAR(10) = '')
AS
	BEGIN
		IF @TIPO = 'INSERT'
			BEGIN
				INSERT INTO [dbo].[ALERTA]
					   ([IDSTOCK],
					   [IDPERSONA],
					   [CANTIDADMINIMA])
				VALUES
					   (@STOCK,
					   @USUARIO,
					   @MINIMO)
			END
		IF @TIPO = 'SELECTALL'
			BEGIN
				SELECT [IDALERTA],
						[IDSTOCK],
						[IDPERSONA],
						[CANTIDADMINIMA]
				FROM [dbo].[ALERTA]
			END
		IF @TIPO = 'SELECTONE'
			BEGIN
				SELECT [IDALERTA],
						[IDSTOCK],
					   [IDPERSONA],
					   [CANTIDADMINIMA]
				FROM [dbo].[ALERTA]
				WHERE ([IDALERTA] = @ID OR [IDSTOCK] = @STOCK OR [IDPERSONA] = @USUARIO) 
			END
		IF @TIPO = 'UPDATE'
			BEGIN
				IF (@STOCK IS NOT NULL) 
					BEGIN
						UPDATE [dbo].[ALERTA]
						SET [IDSTOCK] = @STOCK
						WHERE [IDALERTA] = @ID
					END
				IF (@USUARIO IS NOT NULL) 
					BEGIN
						UPDATE [dbo].[ALERTA]
						SET	[IDPERSONA] = @USUARIO
						WHERE [IDALERTA] = @ID
					END
				IF (@MINIMO IS NOT NULL) 
					BEGIN
						UPDATE [dbo].[ALERTA]
						SET	[CANTIDADMINIMA] = @MINIMO
						WHERE [IDALERTA] = @ID
					END
				
			END
		IF @TIPO = 'DELETE'
			BEGIN
				DELETE FROM [dbo].[ALERTA]
				WHERE [IDALERTA] = @ID
			END
	END
GO
/*procedimientos del CATEGORIA, EXEC CATEGORIAPROC @ID = INT,@DESCRIPCION = VARCHAR(30),@TIPO = NVARCHAR(10);*/
CREATE PROCEDURE CATEGORIAPROC (@ID INT,
								@DESCRIPCION VARCHAR(30),
								@TIPO NVARCHAR(10) = '')
AS
	BEGIN
		IF @TIPO = 'INSERT'
			BEGIN
				INSERT INTO [dbo].[CATEGORIA]
					   ([DESCRIPCION])
				VALUES
					   (@DESCRIPCION)
			END
		IF @TIPO = 'SELECTALL'
			BEGIN
				SELECT [IDCATEGORIA],
						[DESCRIPCION]
				FROM [dbo].[CATEGORIA]
			END
		IF @TIPO = 'SELECTONE'
			BEGIN
				SELECT	[IDCATEGORIA],
						[DESCRIPCION]
				FROM [dbo].[CATEGORIA]
				WHERE [IDCATEGORIA] = @ID
			END
		IF @TIPO = 'UPDATE'
			BEGIN
				IF (@DESCRIPCION IS NOT NULL)
					BEGIN
						UPDATE [dbo].[CATEGORIA]
						SET	[DESCRIPCION] = @DESCRIPCION
						WHERE [IDCATEGORIA] = @ID
					END
			END
		IF @TIPO = 'DELETE'
			BEGIN
				DELETE FROM [dbo].[CATEGORIA]
				WHERE [IDCATEGORIA] = @ID
			END
	END
GO
/*procedimientos del CATEGORIA, EXEC ALERTAPROC @ID=INT,@ALTURA=VARCHAR(6),@CALLE=VARCHAR(30),@CP=INT,@LOCALIDAD=VARCHAR(20),@PROVINCIA=VARCHAR(20),@TIPO=NVARCHAR(10);*/
CREATE PROCEDURE DIRECCIONPROC (@ID INT,
								@ALTURA VARCHAR(6),
								@CALLE VARCHAR(30),
								@CP INT,
								@LOCALIDAD VARCHAR(20),
								@PROVINCIA VARCHAR(20),
								@TIPO NVARCHAR(10) = '')
AS
	BEGIN
		IF @TIPO = 'INSERT'
			BEGIN
				INSERT INTO [dbo].[DIRECCION]
					   ([ALTURA],
					   [CALLE],
					   [CODIGOPOSTAL],
					   [LOCALIDAD],
					   [PROVINCIA])
				VALUES
					   (@ALTURA,
					   @CALLE,
					   @CP,
					   @LOCALIDAD,
					   @PROVINCIA)
			END
		IF @TIPO = 'SELECTALL'
			BEGIN
				SELECT [IDDIRECCION],
						[ALTURA],
						[CALLE],
						[CODIGOPOSTAL],
						[LOCALIDAD],
						[PROVINCIA]
				FROM [dbo].[DIRECCION]
			END
		IF @TIPO = 'SELECTONE'
			BEGIN
				SELECT [IDDIRECCION],
						[ALTURA],
						[CALLE],
						[CODIGOPOSTAL],
						[LOCALIDAD],
						[PROVINCIA]
				FROM [dbo].[DIRECCION]
				WHERE (([IDDIRECCION] = @ID) OR ([CALLE] = @CALLE AND [ALTURA] = @ALTURA AND [LOCALIDAD] = @LOCALIDAD))
			END
		IF @TIPO = 'UPDATE'
			BEGIN
				IF (@ALTURA IS NOT NULL) 
					BEGIN
						UPDATE [dbo].[DIRECCION]
						SET [ALTURA] = @ALTURA
						WHERE [IDDIRECCION] = @ID
					END
				IF (@CALLE IS NOT NULL) 
					BEGIN
						UPDATE [dbo].[DIRECCION]
						SET [CALLE] = @CALLE
						WHERE [IDDIRECCION] = @ID
					END
				IF (@CP IS NOT NULL) 
					BEGIN
						UPDATE [dbo].[DIRECCION]
						SET [CODIGOPOSTAL] = @CP
						WHERE [IDDIRECCION] = @ID
					END
				IF (@LOCALIDAD IS NOT NULL) 
					BEGIN
						UPDATE [dbo].[DIRECCION]
						SET [LOCALIDAD] = @LOCALIDAD
						WHERE [IDDIRECCION] = @ID
					END
				IF (@PROVINCIA IS NOT NULL) 
					BEGIN
						UPDATE [dbo].[DIRECCION]
						SET [PROVINCIA] = @PROVINCIA
						WHERE [IDDIRECCION] = @ID
					END
			END
		IF @TIPO = 'DELETE'
			BEGIN
				DELETE FROM [dbo].[DIRECCION]
				WHERE [IDDIRECCION] = @ID
			END
	END
GO
/*procedimientos del DETALLEORDEN, EXEC DETALLEPROC @ID = SMALLINT,@ORDEN=INT,@PRODUCTO=INT,@CANTIDAD=SMALLINT,@TIPO = '';*/
CREATE PROCEDURE DETALLEPROC	(@ID SMALLINT,
								@ORDEN INT,
								@PRODUCTO INT,
								@CANTIDAD SMALLINT,
								@TIPO NVARCHAR(10) = '')
AS
	BEGIN
		IF @TIPO = 'INSERT'
			BEGIN
				INSERT INTO [dbo].[DETALLEORDEN]
					   ([IDPRODUCTO],
					   [CANTIDAD])
				VALUES
					   (@PRODUCTO,
					   @CANTIDAD)
			END
		IF @TIPO = 'SELECTALL'
			BEGIN
				SELECT [IDDETALLE],
						[IDORDEN],
						[IDPRODUCTO],
						[CANTIDAD]
				FROM [dbo].[DETALLEORDEN]
			END
		IF @TIPO = 'SELECTONE'
			BEGIN
				SELECT [IDDETALLE],
						[IDORDEN],
						[IDPRODUCTO],
						[CANTIDAD]
				FROM [dbo].[DETALLEORDEN]
				WHERE (([IDORDEN] = @ORDEN AND [IDDETALLE] = @ID) OR [IDORDEN] = @ORDEN)
			END
		IF @TIPO = 'UPDATE'
			BEGIN
				IF (@PRODUCTO IS NOT NULL)
					BEGIN
						UPDATE [dbo].[DETALLEORDEN]
						SET	[IDPRODUCTO] = @PRODUCTO
						WHERE [IDDETALLE] = @ID
					END
				IF (@CANTIDAD IS NOT NULL)
					BEGIN
						UPDATE [dbo].[DETALLEORDEN]
						SET	[CANTIDAD] = @CANTIDAD
						WHERE [IDDETALLE] = @ID
					END
			END
		IF @TIPO = 'DELETE'
			BEGIN
				DELETE FROM [dbo].[DETALLEORDEN]
				WHERE (([IDORDEN] = @ORDEN AND [IDDETALLE] = @ID) OR [IDORDEN] = @ORDEN)
			END
	END
GO