DBCC CHECKIDENT ('[DIRECCION]', RESEED, 0)
DELETE FROM DIRECCION WHERE [IDDIRECCION] <> 0

DBCC CHECKIDENT ('[CATEGORIA]', RESEED, 0)
DELETE FROM CATEGORIA WHERE [IDCATEGORIA] <> 0

DBCC CHECKIDENT ('[ROL]', RESEED, 0)
DELETE FROM ROL WHERE [IDROL] <> 0

DBCC CHECKIDENT ('[PERSONA]', RESEED, 0)
DELETE FROM PERSONA WHERE [IDPERSONA] <> 0

DBCC CHECKIDENT ('[PROVEEDOR]', RESEED, 0)
DELETE FROM PROVEEDOR WHERE [IDPROVEEDOR] <> 0

DBCC CHECKIDENT ('[USUARIO]', RESEED, 0)
DELETE FROM USUARIO WHERE [IDLEGAJO] <> 0

DBCC CHECKIDENT ('[ORDEN]', RESEED, 0)
DELETE FROM ORDEN WHERE [IDORDEN] <> 0

DBCC CHECKIDENT ('[PRODUCTO]', RESEED, 0)
DELETE FROM PRODUCTO WHERE [IDPRODUCTO] <> 0
       
DBCC CHECKIDENT ('[DETALLEORDEN]', RESEED, 0)
DELETE FROM DETALLEORDEN WHERE [IDDETALLE] <> 0

DBCC CHECKIDENT ('[STOCK]', RESEED, 0)
DELETE FROM STOCK WHERE [IDSTOCK] <> 0

DBCC CHECKIDENT ('[ALERTA]', RESEED, 0)
DELETE FROM ALERTA WHERE [IDALERTA] <> 0