DBCC CHECKIDENT ('[alerta]', RESEED, 0)
DELETE FROM [dbo].alerta WHERE id_alerta <> 0

DBCC CHECKIDENT ('[CATEGORIA]', RESEED, 0)
DELETE FROM CATEGORIA WHERE [id_categoria] <> 0

DBCC CHECKIDENT ('[DETALLE_ORDEN]', RESEED, 0)
DELETE FROM detalle_orden WHERE [id_detalle_orden] <> 0

DBCC CHECKIDENT ('[direccion]', RESEED, 0)
DELETE FROM [dbo].direccion WHERE id <> 0

DBCC CHECKIDENT ('[ORDEN]', RESEED, 0)
DELETE FROM ORDEN WHERE [ID] <> 0

DELETE FROM orden_compra WHERE [ID_ORDEN] <> 0

DBCC CHECKIDENT ('[persona]', RESEED, 0)
DELETE FROM [dbo].[persona] WHERE id <> 0

DBCC CHECKIDENT ('[PRODUCTO]', RESEED, 0)
DELETE FROM PRODUCTO WHERE [ID_PRODUCTO] <> 0

DBCC CHECKIDENT ('[PROVEEDOR]', RESEED, 0)
DELETE FROM PROVEEDOR WHERE [ID_PROVEEDOR] <> 0

DBCC CHECKIDENT ('[STOCK]', RESEED, 0)
DELETE FROM STOCK WHERE [ID_STOCK] <> 0

DELETE FROM USUARIO WHERE [id_persona] <> 0
