
--CUIDADO AL CORRER TODO SE LIMPIA LA BBDD------------



DBCC CHECKIDENT ('[alerta]', RESEED, 0)
DELETE FROM [dbo].[alerta] WHERE [id_alerta] <> 0

DBCC CHECKIDENT ('[DETALLE_ORDEN]', RESEED, 0)
DELETE FROM detalle_orden WHERE [id_detalle_orden] <> 0

DELETE FROM orden_venta WHERE [ID_ORDEN] <> 0

DELETE FROM orden_compra WHERE [ID_ORDEN] <> 0

DBCC CHECKIDENT ('[tarjeta]', RESEED, 0)
DELETE FROM tarjeta WHERE id_tarjeta <> 0

DBCC CHECKIDENT ('[ORDEN]', RESEED, 0)
DELETE FROM ORDEN WHERE [ID] <> 0

DBCC CHECKIDENT ('[SESION]', RESEED, 0)
DELETE FROM SESION WHERE id <> 0

DELETE FROM USUARIO WHERE [id_persona] <> 0

DBCC CHECKIDENT ('[PROVEEDOR]', RESEED, 0)
DELETE FROM PROVEEDOR WHERE [ID_PROVEEDOR] <> 0

DBCC CHECKIDENT ('[STOCK]', RESEED, 0)
DELETE FROM STOCK WHERE [ID_STOCK] <> 0

DBCC CHECKIDENT ('[CLIENTE]', RESEED, 0)
DELETE FROM CLIENTE WHERE id_cliente <> 0

DBCC CHECKIDENT ('[persona]', RESEED, 0)
DELETE FROM [dbo].[persona] WHERE id <> 0

DELETE FROM permiso_por_rol WHERE id_rol <> 0

DBCC CHECKIDENT ('[ROL]', RESEED, 0)
DELETE FROM ROL WHERE [id] <> 0

DBCC CHECKIDENT ('[permiso]', RESEED, 0)
DELETE FROM permiso WHERE id <> 0

DBCC CHECKIDENT ('[CATEGORIA]', RESEED, 0)
DELETE FROM CATEGORIA WHERE [id_categoria] <> 0

DBCC CHECKIDENT ('[direccion]', RESEED, 0)
DELETE FROM [dbo].direccion WHERE id <> 0

DBCC CHECKIDENT ('[PRODUCTO]', RESEED, 0)
DELETE FROM PRODUCTO WHERE [ID_PRODUCTO] <> 0

DBCC CHECKIDENT ('[METODO_PAGO]', RESEED, 0)
DELETE FROM metodo_pago WHERE id_metodo_pago <> 0