/*procedimientos de ALERTA, 
EXEC ALERTAPROC @ID = INT,@STOCK = INT,@USUARIO = INT,@MINIMO = INT,@TIPO = NVARCHAR10;
*/ 
CREATE PROCEDURE ALERTAPROC	(@ID INT,
							@STOCK INT,
							@USUARIO INT,
							@MINIMO INT,
							@TIPO NVARCHAR(10) = '')
AS
	BEGIN
		IF @TIPO = 'INSERT'
			BEGIN
				INSERT INTO [dbo].[ALERTA]
					   ([IDSTOCK],
					   [IDPERSONA],
					   [CANTIDADMINIMA])
				VALUES
					   (@STOCK,
					   @USUARIO,
					   @MINIMO)
			END
		IF @TIPO = 'SELECT'
			BEGIN
				SELECT [IDALERTA],
						[IDSTOCK],
						[IDPERSONA],
						[CANTIDADMINIMA]
				FROM [dbo].[ALERTA]
			END
		IF @TIPO = 'UPDATE'
			BEGIN
				IF (@STOCK IS NOT NULL) 
					BEGIN
						UPDATE [dbo].[ALERTA]
						SET [IDSTOCK] = @STOCK
						WHERE [IDALERTA] = @ID
					END
				IF (@USUARIO IS NOT NULL) 
					BEGIN
						UPDATE [dbo].[ALERTA]
						SET	[IDPERSONA] = @USUARIO
						WHERE [IDALERTA] = @ID
					END
				IF (@MINIMO IS NOT NULL) 
					BEGIN
						UPDATE [dbo].[ALERTA]
						SET	[CANTIDADMINIMA] = @MINIMO
						WHERE [IDALERTA] = @ID
					END
				
			END
		IF @TIPO = 'DELETE'
			BEGIN
				DELETE FROM [dbo].[ALERTA]
				WHERE [IDALERTA] = @ID
			END
	END
GO

/*procedimientos de CATEGORIA, 
EXEC CATEGORIAPROC @ID = INT,@DESCRIPCION = VARCHAR30,@HABILITADO = DATETIME,@TIPO = NVARCHAR10;
*/
CREATE PROCEDURE CATEGORIAPROC (@ID INT,
								@DESCRIPCION VARCHAR(30),
								@HABILITADO DATETIME,
								@TIPO NVARCHAR(10) = '')
AS
	BEGIN
		IF @TIPO = 'INSERT'
			BEGIN
				INSERT INTO [dbo].[CATEGORIA]
					   ([DESCRIPCION]
					   ,[HABILITADO])
				VALUES
					   (@DESCRIPCION
					   ,@HABILITADO)
			END
		IF @TIPO = 'ESTADO'
			BEGIN
				UPDATE [dbo].[CATEGORIA]
				SET	[HABILITADO] = @HABILITADO 
				WHERE [IDCATEGORIA] = @ID
			END
		IF @TIPO = 'SELECT'
			BEGIN
				SELECT [IDCATEGORIA],
						[DESCRIPCION],
						[HABILITADO]
				FROM [dbo].[CATEGORIA]
			END
		IF @TIPO = 'UPDATE'
			BEGIN
				IF (@DESCRIPCION IS NOT NULL)
					BEGIN
						UPDATE [dbo].[CATEGORIA]
						SET	[DESCRIPCION] = @DESCRIPCION
						WHERE [IDCATEGORIA] = @ID
					END
			END
		IF @TIPO = 'DELETE'
			BEGIN
				DELETE FROM [dbo].[CATEGORIA]
				WHERE [IDCATEGORIA] = @ID
			END
	END
GO

/*procedimientos de DIRECCION, 
EXEC DIRECCIONPROC @ID=INT,@ALTURA=VARCHAR(6),@CALLE=VARCHAR(30),@CP=VARCHAR(20),@LOCALIDAD=VARCHAR(30),@PROVINCIA=VARCHAR(30),@TIPO=NVARCHAR(10);
*/
CREATE PROCEDURE DIRECCIONPROC (@ID INT,
								@ALTURA VARCHAR(6),
								@CALLE VARCHAR(30),
								@CP VARCHAR(20),
								@LOCALIDAD VARCHAR(30),
								@PROVINCIA VARCHAR(30),
								@TIPO NVARCHAR(10) = '')
AS
	BEGIN
		IF @TIPO = 'INSERT'
			BEGIN
				INSERT INTO [dbo].[DIRECCION]
					   ([ALTURA],
					   [CALLE],
					   [CODIGOPOSTAL],
					   [LOCALIDAD],
					   [PROVINCIA])
				VALUES
					   (@ALTURA,
					   @CALLE,
					   @CP,
					   @LOCALIDAD,
					   @PROVINCIA)
			END
		IF @TIPO = 'SELECT'
			BEGIN
				SELECT [IDDIRECCION],
						[ALTURA],
						[CALLE],
						[CODIGOPOSTAL],
						[LOCALIDAD],
						[PROVINCIA]
				FROM [dbo].[DIRECCION]
			END
		IF @TIPO = 'UPDATE'
			BEGIN
				IF (@ALTURA IS NOT NULL) 
					BEGIN
						UPDATE [dbo].[DIRECCION]
						SET [ALTURA] = @ALTURA
						WHERE [IDDIRECCION] = @ID
					END
				IF (@CALLE IS NOT NULL) 
					BEGIN
						UPDATE [dbo].[DIRECCION]
						SET [CALLE] = @CALLE
						WHERE [IDDIRECCION] = @ID
					END
				IF (@CP IS NOT NULL) 
					BEGIN
						UPDATE [dbo].[DIRECCION]
						SET [CODIGOPOSTAL] = @CP
						WHERE [IDDIRECCION] = @ID
					END
				IF (@LOCALIDAD IS NOT NULL) 
					BEGIN
						UPDATE [dbo].[DIRECCION]
						SET [LOCALIDAD] = @LOCALIDAD
						WHERE [IDDIRECCION] = @ID
					END
				IF (@PROVINCIA IS NOT NULL) 
					BEGIN
						UPDATE [dbo].[DIRECCION]
						SET [PROVINCIA] = @PROVINCIA
						WHERE [IDDIRECCION] = @ID
					END
			END
		IF @TIPO = 'DELETE'
			BEGIN
				DELETE FROM [dbo].[DIRECCION]
				WHERE [IDDIRECCION] = @ID
			END
	END
GO

/*procedimientos de DETALLEORDEN, 
EXEC DETALLEPROC @ID = SMALLINT,@ORDEN=INT,@PRODUCTO=INT,@CANTIDAD=SMALLINT,@TIPO = '';
*/
CREATE PROCEDURE DETALLEPROC	(@ID SMALLINT,
								@ORDEN INT,
								@PRODUCTO INT,
								@CANTIDAD SMALLINT,
								@TIPO NVARCHAR(10) = '')
AS
	BEGIN
		IF @TIPO = 'INSERT'
			BEGIN
				INSERT INTO [dbo].[DETALLEORDEN]
					   ([IDPRODUCTO],
					   [IDORDEN],
					   [CANTIDAD])
				VALUES
					   (@PRODUCTO,
					   @ORDEN,
					   @CANTIDAD)
			END
		IF @TIPO = 'SELECT'
			BEGIN
				SELECT	[IDDETALLE],
						[IDORDEN],
						[IDPRODUCTO],
						[CANTIDAD]
				FROM [dbo].[DETALLEORDEN]
			END
		IF @TIPO = 'UPDATE' /*No deberia poder asociar detalle a otro idOrden*/
			BEGIN
				IF (@PRODUCTO IS NOT NULL)
					BEGIN
						UPDATE [dbo].[DETALLEORDEN]
						SET	[IDPRODUCTO] = @PRODUCTO
						WHERE [IDDETALLE] = @ID
					END
				IF (@CANTIDAD IS NOT NULL)
					BEGIN
						UPDATE [dbo].[DETALLEORDEN]
						SET	[CANTIDAD] = @CANTIDAD
						WHERE [IDDETALLE] = @ID
					END
			END
		IF @TIPO = 'DELETE'
			BEGIN
				DELETE FROM [dbo].[DETALLEORDEN]
				WHERE ([IDDETALLE] = @ID AND [IDORDEN] = @ORDEN)
			END
	END
GO

/*procedimientos de ORDEN, EXEC ORDENPROD @ID=INT,@USUARIO=INT,@HABILITADO=DATETIME,@TIPO=NVARCHAR(10);*/
CREATE PROCEDURE ORDENPROC	(@ID INT,
							@USUARIO INT,
							@HABILITADO DATETIME,
							@TIPO NVARCHAR(10))
AS
	BEGIN
		IF @TIPO = 'INSERT'
			BEGIN
				INSERT INTO [dbo].[ORDEN]
					   ([IDPERSONA],
					   [HABILITADO])
				VALUES
					   (@USUARIO,
					   @HABILITADO)
			END
		IF @TIPO = 'SELECT'
			BEGIN
				SELECT [IDORDEN],
						[IDPERSONA],
						[HABILITADO]
				FROM [dbo].[ORDEN]
			END
		IF @TIPO = 'ESTADO'
			BEGIN
				UPDATE [dbo].[ORDEN]
				SET	[HABILITADO] = @HABILITADO 
				WHERE [IDORDEN] = @ID
			END
		IF @TIPO = 'UPDATE'
			BEGIN
				IF (@USUARIO IS NOT NULL)
					BEGIN
						UPDATE [dbo].[ORDEN]
						SET	[IDPERSONA] = @USUARIO 
						WHERE [IDORDEN] = @ID
					END
			END
		IF @TIPO = 'DELETE'
			BEGIN
				DELETE FROM [dbo].[ORDEN]
				WHERE [IDORDEN] = @ID
			END
	END
GO

/*procedimientos de ORDENCOMPRA, 
EXEC ORDENCOMPRAPROC @ID=INT,@PROVEEDOR=INT,@USUARIO=INT,@FECHA=DATETIME,@TIPO=NVARCHAR(10);
*/
CREATE PROCEDURE ORDENCOMPRAPROC	(@ID INT,
									@PROVEEDOR INT,
									@USUARIO INT,
									@FECHA DATETIME,
									@TIPO NVARCHAR(10) = '')
AS
	BEGIN
		IF @TIPO = 'INSERT'
			BEGIN
				INSERT INTO [dbo].[ORDENCOMPRA]
					   ([IDPROVEEDOR],
					   [IDPERSONA],
					   [FECHAAPROVACION])
				VALUES
					   (@PROVEEDOR,
					   @USUARIO,
					   @FECHA)
			END
		IF @TIPO = 'SELECT'
			BEGIN
				SELECT	[IDORDEN],
						[IDPROVEEDOR],
						[IDPERSONA],
						[FECHAAPROVACION]
				FROM [dbo].[ORDENCOMPRA]
			END
		IF @TIPO = 'UPDATE'
			BEGIN
				IF (@PROVEEDOR IS NOT NULL)
					BEGIN
						UPDATE [dbo].[ORDENCOMPRA]
						SET	[IDPROVEEDOR] = @PROVEEDOR
						WHERE [IDORDEN] = @ID
					END
				IF (@USUARIO IS NOT NULL AND @FECHA IS NOT NULL)
					BEGIN
						UPDATE [dbo].[ORDENCOMPRA]
						SET	[IDPERSONA] = @USUARIO,
							[FECHAAPROVACION] = @FECHA
						WHERE [IDORDEN] = @ID
					END
			END
		IF @TIPO = 'DELETE'
			BEGIN
				DELETE FROM [dbo].[ORDENCOMPRA]
				WHERE [IDORDEN] = @ID
			END
	END
GO

/*procedimientos de PERSONA, 
EXEC PERSONAPROC @ID=INT,@DIRECCION=INT,@DNI=INT,@NOMBRE=VARCHAR(30),@APELLIDO=VARCHAR(30),@TIPO=NVARCHAR(10);
*/
CREATE PROCEDURE PERSONAPROC	(@ID INT,
						@DIRECCION INT,
						@DNI INT,
						@NOMBRE VARCHAR(30),
						@APELLIDO VARCHAR(30),
						@TIPO NVARCHAR(10) = '')
AS
	BEGIN
		IF @TIPO = 'INSERT'
			BEGIN
				INSERT INTO [dbo].[PERSONA]
					   ([IDDIRECCION],
					   [DNI],
					   [NOMBRE],
					   [APELLIDO])
				VALUES
					   (@DIRECCION,
					   @DNI,
					   @NOMBRE,
					   @APELLIDO)
			END
		IF @TIPO = 'SELECT'
			BEGIN
				SELECT	[IDPERSONA],
						[IDDIRECCION],
						[DNI],
						[NOMBRE],
						[APELLIDO]
				FROM [dbo].[PERSONA]
			END
		IF @TIPO = 'UPDATE'
			BEGIN
				IF (@DIRECCION IS NOT NULL)
					BEGIN
						UPDATE [dbo].[PERSONA]
						SET	[IDDIRECCION] = @DIRECCION
						WHERE [IDPERSONA] = @ID
					END
				IF (@DNI IS NOT NULL)
					BEGIN
						UPDATE [dbo].[PERSONA]
						SET	[DNI] = @DNI
						WHERE [IDPERSONA] = @ID
					END
				IF (@NOMBRE IS NOT NULL)
					BEGIN
						UPDATE [dbo].[PERSONA]
						SET	[NOMBRE] = @NOMBRE
						WHERE [IDPERSONA] = @ID
					END
				IF (@APELLIDO IS NOT NULL)
					BEGIN
						UPDATE [dbo].[PERSONA]
						SET	[APELLIDO] = @APELLIDO
						WHERE [IDPERSONA] = @ID
					END
			END
		IF @TIPO = 'DELETE'
			BEGIN
				DELETE FROM [dbo].[PERSONA]
				WHERE [IDPERSONA] = @ID
			END
	END
GO

/*procedimientos de PRODUCTO, EXEC PRODUCTOPROC @ID=INT,@CATEGORIA=SMALLINT,@NOMBRE=NVARCHAR(50),@COMPRA REAL,@VENTA REAL,@HABILITADO = DATETIME,@TIPO=NVARCHAR(10);*/
CREATE PROCEDURE PRODUCTOPROC	(@ID INT,
						@CATEGORIA SMALLINT,
						@NOMBRE NVARCHAR(50),
						@VENTA REAL,
						@COMPRA REAL,
						@HABILITADO DATETIME,
						@TIPO NVARCHAR(10) = '')
AS
	BEGIN
		IF @TIPO = 'INSERT'
			BEGIN
				INSERT INTO [dbo].[PRODUCTO]
					   ([IDCATEGORIA],
					   [NOMBRE],
					   [PRECIOCOMPRA],
					   [PRECIOVENTA],
					   [HABILITADO])
				VALUES
					   (@CATEGORIA,
					   @NOMBRE,
					   @COMPRA,
					   @VENTA,
					   @HABILITADO)
			END
		IF @TIPO = 'SELECT'
			BEGIN
				SELECT	[IDPRODUCTO],
						[IDCATEGORIA],
						[NOMBRE],
						[PRECIOCOMPRA],
						[PRECIOVENTA],
						[HABILITADO]
				FROM [dbo].[PRODUCTO]
			END
		IF @TIPO = 'ESTADO'
			BEGIN
				UPDATE [dbo].[PRODUCTO]
				SET	[HABILITADO] = @HABILITADO 
				WHERE [IDPRODUCTO] = @ID
			END
		IF @TIPO = 'UPDATE'
			BEGIN
				IF (@CATEGORIA IS NOT NULL)
					BEGIN
						UPDATE [dbo].[PRODUCTO]
						SET	[IDCATEGORIA] = @CATEGORIA
						WHERE [IDPRODUCTO] = @ID
					END
				IF (@NOMBRE IS NOT NULL)
					BEGIN
						UPDATE [dbo].[PRODUCTO]
						SET	[NOMBRE] = @NOMBRE
						WHERE [IDPRODUCTO] = @ID
					END
				IF (@COMPRA IS NOT NULL)
					BEGIN
						UPDATE [dbo].[PRODUCTO]
						SET	[PRECIOCOMPRA] = @COMPRA
						WHERE [IDPRODUCTO] = @ID
					END
				IF (@VENTA IS NOT NULL)
					BEGIN
						UPDATE [dbo].[PRODUCTO]
						SET	[PRECIOVENTA] = @VENTA
						WHERE [IDPRODUCTO] = @ID
					END
			END
		IF @TIPO = 'DELETE'
			BEGIN
				DELETE FROM [dbo].[PRODUCTO]
				WHERE [IDPRODUCTO] = @ID OR ([NOMBRE] = @NOMBRE AND [IDCATEGORIA] = @CATEGORIA)
			END
	END
GO

/*procedimientos de PROVEEDOR, 
EXEC PROVEEDORPROC @ID=INT,@DIRECCION=INT,@CUIL=VARCHAR(13),@RAZONSOCIAL=VARCHAR(30),@HABILITADO = DATETIME,@TIPO=NVARCHAR(10);
*/
CREATE PROCEDURE PROVEEDORPROC	(@ID INT,
						@DIRECCION INT,
						@CUIL VARCHAR(13),
						@RAZONSOCIAL VARCHAR(30) ,
						@HABILITADO DATETIME,
						@TIPO NVARCHAR(10) = '')
AS
	BEGIN
		IF @TIPO = 'INSERT'
			BEGIN
				INSERT INTO [dbo].[PROVEEDOR]
					   ([IDDIRECCION],
					   [CUIL],
					   [RAZONSOCIAL],
					   [HABILITADO])
				VALUES
					   (@DIRECCION,
					   @CUIL,
					   @RAZONSOCIAL,
					   @HABILITADO)
			END
		IF @TIPO = 'SELECT'
			BEGIN
				SELECT	[IDPROVEEDOR],
						[IDDIRECCION],
						[CUIL],
						[RAZONSOCIAL],
						[HABILITADO]
				FROM [dbo].[PROVEEDOR]
			END
		IF @TIPO = 'ESTADO'
			BEGIN
				UPDATE [dbo].[PROVEEDOR]
				SET	[HABILITADO] = @HABILITADO 
				WHERE [IDPROVEEDOR] = @ID
			END
		IF @TIPO = 'UPDATE'
			BEGIN
				IF (@DIRECCION IS NOT NULL)
					BEGIN
						UPDATE [dbo].[PROVEEDOR]
						SET	[IDDIRECCION] = @DIRECCION
						WHERE [IDPROVEEDOR] = @ID
					END
				IF (@CUIL IS NOT NULL)
					BEGIN
						UPDATE [dbo].[PROVEEDOR]
						SET	[CUIL] = @CUIL
						WHERE [IDPROVEEDOR] = @ID
					END
				IF (@RAZONSOCIAL IS NOT NULL)
					BEGIN
						UPDATE [dbo].[PROVEEDOR]
						SET	[RAZONSOCIAL] = @RAZONSOCIAL
						WHERE [IDPROVEEDOR] = @ID
					END
			END
		IF @TIPO = 'DELETE'
			BEGIN
				DELETE FROM [dbo].[PROVEEDOR]
				WHERE [IDPROVEEDOR] = @ID
			END
	END
GO

/*procedimientos de ROL, EXEC ROLPROC @ID=INT,@DESCRIPCION=VARCHAR(20),@TIPO=NVARCHAR(10);*/
CREATE PROCEDURE ROLPROC	(@ID INT,
						@DESCRIPCION VARCHAR(20),
						@TIPO NVARCHAR(10) = '')
AS
	BEGIN
		IF @TIPO = 'INSERT'
			BEGIN
				INSERT INTO [dbo].[ROL]
					   ([DESCRIPCIONROL])
				VALUES
					   (@DESCRIPCION)
			END
		IF @TIPO = 'SELECT'
			BEGIN
				SELECT [IDROL],
						[DESCRIPCIONROL]
				FROM [dbo].[ROL]
			END
		IF @TIPO = 'UPDATE'
			BEGIN
				IF (@DESCRIPCION IS NOT NULL)
					BEGIN
						UPDATE [dbo].[ROL]
						SET	[DESCRIPCIONROL] = @DESCRIPCION
						WHERE [IDROL] = @ID
					END
			END
		IF @TIPO = 'DELETE'
			BEGIN
				DELETE FROM [dbo].[ROL]
				WHERE [IDROL] = @ID
			END
	END
GO

/*procedimientos de STOCK, 
EXEC STOCKPROC @ID=INT,@PRODUCTO=INT,@CANTIDAD=INT,@HABILITADO = DATETIME,@TIPO=NVARCHAR(10);
*/
CREATE PROCEDURE STOCKPROC	(@ID INT,
						@PRODUCTO INT,
						@CANTIDAD INT,
						@HABILITADO DATETIME,
						@TIPO NVARCHAR(10) = '')
AS
	BEGIN
		IF @TIPO = 'INSERT'
			BEGIN
				INSERT INTO [dbo].[STOCK]
					   ([IDPRODUCTO],
					   [CANTIDAD],
					   [HABILITADO])
				VALUES
					   (@PRODUCTO,
					   @CANTIDAD,
					   @HABILITADO)
			END
		IF @TIPO = 'SELECT'
			BEGIN
				SELECT	[IDSTOCK],
						[IDPRODUCTO],
						[CANTIDAD],
						[HABILITADO]
				FROM [dbo].[STOCK]
			END
		IF @TIPO = 'ESTADO'
			BEGIN
				UPDATE [dbo].[STOCK]
				SET	[HABILITADO] = @HABILITADO 
				WHERE [IDSTOCK] = @ID
			END
		IF @TIPO = 'UPDATE'
			BEGIN
				IF (@PRODUCTO IS NOT NULL)
					BEGIN
						UPDATE [dbo].[STOCK]
						SET	[IDPRODUCTO] = @PRODUCTO
						WHERE [IDSTOCK] = @ID
					END
				IF (@CANTIDAD IS NOT NULL)
					BEGIN
						UPDATE [dbo].[STOCK]
						SET	[CANTIDAD] = @CANTIDAD
						WHERE [IDSTOCK] = @ID
					END
			END
		IF @TIPO = 'DELETE'
			BEGIN
				DELETE FROM [dbo].[STOCK]
				WHERE [IDSTOCK] = @ID
			END
	END
GO

/*procedimientos de USUARIO, 
EXEC USUARIOPROC @ID=INT,@ROL=TINYINT,@LEGAJO=INT,@HABILITADO = DATETIME,@TIPO=NVARCHAR(10);
*/
CREATE PROCEDURE USUARIOPROC	(@ID INT,
						@ROL TINYINT,
						@LEGAJO INT,
						@HABILITADO DATETIME,
						@TIPO NVARCHAR(10) = '')
AS
	BEGIN
		IF @TIPO = 'INSERT'
			BEGIN
				INSERT INTO [dbo].[USUARIO]
					   ([IDROL],
					   [LEGAJO],
					   [HABILITADO])
				VALUES
					   (@ROL,
					   @LEGAJO,
					   @HABILITADO)
			END
		IF @TIPO ='SELECT'
			BEGIN
				SELECT  [IDPERSONA],
						[IDROL],
						[LEGAJO],
						[HABILITADO]
				FROM [dbo].[USUARIO]
			END
		IF @TIPO = 'ESTADO'
			BEGIN
				UPDATE [dbo].[USUARIO]
				SET	[HABILITADO] = @HABILITADO 
				WHERE [IDPERSONA] = @ID
			END
		IF @TIPO = 'UPDATE'
			BEGIN
				IF (@ROL IS NOT NULL)
					BEGIN
						UPDATE [dbo].[USUARIO]
						SET	[IDROL] = @ROL
						WHERE [IDPERSONA] = @ID
					END
			END
		IF @TIPO = 'DELETE'
			BEGIN
				DELETE FROM [dbo].[USUARIO]
				WHERE [IDPERSONA] = @ID
			END
	END
GO
