USE tecprog;
GO
--ACTUALIZA LOS PRODUCTOS EN STOCK

CREATE TRIGGER PRODUCTOS_ACTUALIZADOS_STOCK ON STOCK

AFTER INSERT ON DETALLEORDEN FOR EACH ROW
DECLARE

BEGIN
	UPDATE PRODUCTO
	SET CANTIDADSTOCK = CANTIDADSTOCK - :NEW.CANTIDAD
	WHERE IDPRODUCTO = :NEW.IDPRODUCTO;



END


GO


CREATE PROCEDURE SP_insertarproducto(@nombre varchar (50),@precioventa SMALLMONEY,@preciocompra	SMALLMONEY)

AS 
BEGIN
	INSERT INTO PRODUCTO(NOMBRE,PRECIOVENTA,PRECIOCOMPRA)
		VALUES (@nombre,@precioventa,@preciocompra)
END 
GO

EXEC SP_insertarproducto'ARTICULO1',2300,2000



