IF object_id('VISTADEPOSITO') is not null
 DROP PROCEDURE VISTADEPOSITO;

CREATE PROCEDURE VISTADEPOSITO AS 
SELECT S.CANTIDAD AS 'Cantidad',
P.NOMBRE AS 'Nombre producto'
from [dbo].[PRODUCTO] AS P 
INNER JOIN [dbo].STOCK AS S
ON S.IDPRODUCTO= P.IDPRODUCTO; 
GO

EXEC VISTADEPOSITO;

IF object_id('VISTA_PRODUCTO') is not null
  DROP PROCEDURE VISTA_PRODUCTO;

	   CREATE PROCEDURE VISTA_PRODUCTO	AS 
	   SELECT S.NOMBRE AS 'Nombre',
	   S.PRECIOCOMPRA AS 'Precio de compra',
	   S.PRECIOVENTA AS 'Precio de venta',
	   A.DESCRIPCION AS 'Categoria'
	   FROM [dbo].[CATEGORIA] AS A
	   INNER JOIN [dbo].[PRODUCTO] AS S 
	   ON S.IDCATEGORIA = A.IDCATEGORIA;
	   GO

	   EXECUTE VISTA_PRODUCTO;

 IF object_id('VISTA_DETALLEORDEN') is not null
 DROP PROCEDURE VISTA_DETALLEORDEN;

	   CREATE PROCEDURE VISTA_DETALLEORDEN AS 
	   SELECT D.IDORDEN AS 'ID',
	   D.CANTIDAD AS 'Cantidad',
	   O.FECHAAPROVACION  AS 'Fecha aprobacion'
	   FROM DETALLEORDEN AS D,
	   ORDENCOMPRA AS O,
		PROVEEDOR AS P  
		WHERE D.IDORDEN = O.IDORDEN
		AND O.IDPERSONA = P.IDPROVEEDOR
		ORDER BY D.IDORDEN

	   EXECUTE VISTA_DETALLEORDEN;

 IF object_id('VISTACATEGORIA') is not null
 DROP PROCEDURE VISTACATEGORIA;

 CREATE PROCEDURE VISTACATEGORIA AS 
 SELECT C.DESCRIPCION AS 'Descripcion',
 C.IDCATEGORIA AS 'id'
 FROM [dbo].[CATEGORIA] AS C
 GO

 EXECUTE VISTACATEGORIA;
